language: python
cache: pip
python: "3.7"
dist: xenial  # required for Python 3.7
sudo: true  # required for Python 3.7
services: postgresql
addons:
  # TravisCI uses 9.2 by default
  postgresql: "9.6"
install: pip install -r requirements.txt
script: make test
