language: python
python: "3.7"
cache: pip
dist: xenial
services: postgresql
addons:
  postgresql: "9.6"
install: pip install -r requirements.txt
script:
  - make test
  - make ext/test

branches:
  only:
    - master
notifications:
  email: false
