language: python
python: "3.6"  # TravisCI doesn't support 3.7 https://github.com/travis-ci/travis-ci/issues/9815
cache: pip
services: postgresql
addons:
  # TravisCI uses 9.2 by default
  postgresql: "9.6"
install: pip install -r requirements.txt
script: make test
