# Generated by Django 2.0.7 on 2018-07-16 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', help_text='ISO4217 Currency Code', max_length=3),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tracker.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('property', 'identifier')},
        ),
    ]
