# Generated by Django 2.0.7 on 2018-07-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180716_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_price_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_drop_day',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_drop_week',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='compacted',
            field=models.BooleanField(default=False),
        ),
    ]
