# Generated by Django 2.0.7 on 2018-07-20 17:11

import apps.personalization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180719_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.CharField(default=apps.personalization.models.pkgen, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
