# Generated by Django 2.1 on 2018-08-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180720_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_drop_week',
            new_name='price_drop_long',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_drop_day',
            new_name='price_drop_short',
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, help_text='Cheapest price seen', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_base',
            field=models.DecimalField(decimal_places=2, help_text='Highest price seen, typically the MSRP', max_digits=8, null=True),
        ),
    ]
