# Generated by Django 2.1 on 2018-08-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180720_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_base',
            field=models.DecimalField(decimal_places=2, help_text='Highest price seen, typically the MSRP', max_digits=8, null=True),
        ),
    ]
