# Generated by Django 2.0.7 on 2018-07-20 16:57

import apps.personalization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id',
        ),
        migrations.AddField(
            model_name='list',
            name='key',
            field=models.CharField(default=apps.personalization.models.pkgen, max_length=9, primary_key=True, serialize=False),
        ),
    ]
